language: python

# Version to Test Against
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# Install Dependencies
install:
    - pip install nose coveralls PyYAML mock

# Run Tests
script:
    - './run_tests.sh'

after_success:
    - coveralls
