language: python

# Version to Test Against
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

# Install Dependencies
install:
    - pip install nose coveralls PyYAML mock

# Run Tests
script:
    - './run_tests.sh'

after_success:
    - coveralls
